name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: running py_test
      id: running-py_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: running py_test
        setup-command: ''
        command: pytest 01/
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUNNING-PY_TEST_RESULTS: "${{steps.running-py_test.outputs.result}}"
      with:
        runners: running-py_test
